@startuml
'https://plantuml.com/sequence-diagram

entity user {
* id: VARCHAR(50)
--
name: VARCHAR(255)
email: VARCHAR(255)
password: VARCHAR(255)
role: TEXT
last_login: LONG
created_at: LONG
}

entity pipeline {
* id: VARCHAR(50)
--
* nip: VARCHAR(50)
name: VARCHAR(255)
phone_number: VARCHAR(20)
address: TEXT
status: enum(FOLLOW_UP, DEAL, LOST)
product_type: INTEGER
prospect_date: LONG
referral_user: VARCHAR(50)
}

entity product_type {
 * id: INTEGER (AUTO_INCREMENT)
 --
 name: VARCHAR(100)
}

user --{ pipeline

pipeline --{ product_type

@enduml